### ISSUE TITLE
TODO: Fix page width / ActionCards size

### ISSUE THREAD

**Issue by dav1dn** [ajaska/innod-webtier-aid#2]
Frontpage currently views like this on my 13rMBP:

![image](https://cloud.githubusercontent.com/assets/9017009/24989701/65930af4-1fc3-11e7-97f6-1ae8c538560d.png)

We can do this after we're done with fleshing everything out, when we also work on making the site responsive

**Comment by bohuim** [comment]
This is my issue from #1, I'll fix it over the weekend.

p.s. I don't have write access to this repo, so can't assign myself.
